default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: learning_word_development

test:
  <<: *default
  database: learning_word_test

production:
  <<: *default
  database: learning_word_production
  username: learning_word
  password: <%= ENV['LEARNING_WORD_DATABASE_PASSWORD'] %>
